server:
  port: 8000

spring:
  datasource:
    dynamic:
      primary: ${artifactId}
      druid:
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat, wall, slf4j
        # 连接池初始化大小
        initial-size: 10
        # 最小保留数
        min-idle: 10
        # 最大连接数
        max-active: 50
        # 获取连接的最大等待时间，单位毫秒
        max-wait: 60000
        # 检测关闭空闲连接的间隔时间，单位毫秒
        time-between-eviction-runs-millis: 60000
        # 连接的最小生存时间，，单位毫秒
        min-evictable-idle-time-millis: 300000
        validation-query: select 1
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        pool-prepared-statements: true
      datasource:
        ${artifactId}:
          username: bccm_deve
          password: bccmDEVE123!
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.2.223:3306/${artifactId}?useUnicode=true&autoReconnect=true&characterEncoding=utf-8
        ${artifactId}-slave:
          username: bccm_deve
          password: bccmDEVE123!
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.2.223:3306/${artifactId}?useUnicode=true&autoReconnect=true
  redis:
    database: 0
    host: 10.0.101.208
    port: 6379
    password: It0SVN8R7BZYpJHl
    lettuce:
      pool:
        max-active: 100
        min-idle: 20
        max-idle: 50

log:
  path: /home/beicai/logs

logging:
  config: classpath:logback-spring-online.xml
